version: '3.8'

services:
  backend:
    environment:
      - ENVIRONMENT=production
      - API_WORKERS=4
      - LOG_LEVEL=info
      - PROMETHEUS_ENABLED=true
      - CACHE_ENABLED=true
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

  frontend:
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  redis:
    profiles: []  # Enable by default in production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  prometheus:
    profiles: []  # Enable by default in production

  grafana:
    profiles: []  # Enable by default in production