# API Configuration
server:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 1

model:
  onnx_path: "models/best_model.onnx"
  class_names: ["healthy", "angular_leaf_spot", "bean_rust"]
  input_size: [224, 224]
  confidence_threshold: 0.5

upload:
  max_file_size: 10485760  # 10MB in bytes
  allowed_extensions: [".jpg", ".jpeg", ".png", ".webp"]
  max_batch_size: 10

cors:
  allow_origins: ["http://localhost:3000", "http://127.0.0.1:3000"]
  allow_credentials: true
  allow_methods: ["GET", "POST"]
  allow_headers: ["*"]

logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file: "logs/api.log"
  rotation: "1 day"
  retention: "7 days"

monitoring:
  enable_metrics: true
  metrics_port: 9090