# Training Configuration
model:
  architectures:
    - "resnet50"
    - "efficientnet_b0"
    - "vgg16"
    - "densenet121"
  num_classes: 3
  pretrained: true

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 50
  early_stopping_patience: 10
  weight_decay: 0.0001
  
data:
  image_size: [224, 224]
  train_csv: "train.csv"
  val_csv: "val.csv"
  train_dir: "train"
  val_dir: "val"
  class_names: ["healthy", "angular_leaf_spot", "bean_rust"]
  
augmentation:
  horizontal_flip: 0.5
  vertical_flip: 0.3
  rotation: 15
  brightness: 0.2
  contrast: 0.2
  saturation: 0.2
  hue: 0.1

optimizer:
  type: "adam"
  momentum: 0.9  # for SGD
  
scheduler:
  type: "step"
  step_size: 20
  gamma: 0.1

device: "cuda"  # or "cpu"
seed: 42